import { Plan } from '../types';

export const DEFAULT_PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Plano Grátis',
    description: 'Para quem está começando e quer um cartão digital moderno e funcional.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: {
      maxBioSites: 1,
      maxProducts: 0,
      hasCatalog: false,
      hasPix: false,
      hasWifi: false,
      hasAnalytics: false,
      hasAdvancedTheme: false,
      hasCustomDomain: false,
      hasWhiteLabel: false,
      hasTeam: false,
      maxTeamMembers: 1,
    },
    featuresList: [
      '1 Bio Site ativo',
      'Links e botões ilimitados',
      'Redes sociais e contato direto',
      'QR Code do Bio Site padrão',
      'Compartilhamento inteligente',
      'vCard Salvar Contato no celular',
    ],
  },
  {
    id: 'pro',
    name: 'Plano Pro',
    popular: true,
    description: 'Perfeito para profissionais liberais, lojas, restaurantes e prestadores de serviço.',
    monthlyPrice: 29.90,
    yearlyPrice: 289.00,
    features: {
      maxBioSites: 1,
      maxProducts: 100,
      hasCatalog: true,
      hasPix: true,
      hasWifi: true,
      hasAnalytics: true,
      hasAdvancedTheme: true,
      hasCustomDomain: false,
      hasWhiteLabel: false,
      hasTeam: false,
      maxTeamMembers: 1,
    },
    featuresList: [
      'Tudo do Plano Grátis',
      'Catálogo Digital com produtos & fotos',
      'Botão "Pedir pelo WhatsApp" integrado',
      'Módulo Pix com QR Code & valores sugeridos',
      'Módulo Wi-Fi com QR Code instantâneo',
      'Estatísticas e Analytics completos',
      'Personalização avançada de cores e fontes',
      'Agendamento de horários / serviços',
    ],
  },
  {
    id: 'essential',
    name: 'Plano Essencial',
    description: 'Ideal para quem gerencia filiais, múltiplos negócios ou pequenos empreendedores.',
    monthlyPrice: 69.90,
    yearlyPrice: 670.00,
    features: {
      maxBioSites: 10,
      maxProducts: 500,
      hasCatalog: true,
      hasPix: true,
      hasWifi: true,
      hasAnalytics: true,
      hasAdvancedTheme: true,
      hasCustomDomain: true,
      hasWhiteLabel: false,
      hasTeam: true,
      maxTeamMembers: 3,
    },
    featuresList: [
      'Até 10 Bio Sites profissionais',
      'Catálogo e Pix em todos os sites',
      'Domínio próprio personalizado (ex: seunome.com.br)',
      'Até 3 membros na equipe',
      'Chave de edição exclusiva por bio site',
      'Suporte prioritário via WhatsApp',
    ],
  },
  {
    id: 'freelancer',
    name: 'Plano Freelancer',
    description: 'Para designers, consultores e desenvolvedores que criam sites para seus clientes.',
    monthlyPrice: 129.90,
    yearlyPrice: 1240.00,
    features: {
      maxBioSites: 25,
      maxProducts: 1000,
      hasCatalog: true,
      hasPix: true,
      hasWifi: true,
      hasAnalytics: true,
      hasAdvancedTheme: true,
      hasCustomDomain: true,
      hasWhiteLabel: true,
      hasTeam: true,
      maxTeamMembers: 5,
    },
    featuresList: [
      'Até 25 Bio Sites simultâneos',
      'Domínios próprios ilimitados',
      'Chaves de edição independentes para clientes',
      'Analytics segmentado por cliente',
      'Exportação de dados e relatórios em PDF/CSV',
      'Até 5 membros na equipe',
    ],
  },
  {
    id: 'agency',
    name: 'Plano Agência',
    description: 'Solução definitiva para agências de marketing, publicidade e revendedores de bio sites.',
    monthlyPrice: 249.90,
    yearlyPrice: 2390.00,
    features: {
      maxBioSites: 100,
      maxProducts: 5000,
      hasCatalog: true,
      hasPix: true,
      hasWifi: true,
      hasAnalytics: true,
      hasAdvancedTheme: true,
      hasCustomDomain: true,
      hasWhiteLabel: true,
      hasTeam: true,
      maxTeamMembers: 20,
    },
    featuresList: [
      'Até 100 Bio Sites inclusos',
      'White-Label 100% (Remova a marca NaBio)',
      'Sua própria marca, logotipo e cores',
      'Painel de gestão de múltiplos clientes',
      'Gestão de membros e permissões (RBAC)',
      'Auditoria de acessos e logs de segurança',
      'Gerente de contas dedicado',
    ],
  },
];

export const PLANS = DEFAULT_PLANS;
