import { Template, BioSiteTheme } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'noir-luxury',
    name: 'Noir Studio & Luxury (Preto & Branco)',
    category: 'Moda & Luxo',
    description: 'Design minimalista preto e branco com vídeo de fundo animado, galeria de até 10 fotos por item, vídeos curtos de 15s e selos de novidades.',
    previewThumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Moda & Conceito',
      name: 'Atelier Noir & Blanc',
      commercialName: 'Noir Concept Studio',
      category: 'Moda, Joias & Acessórios',
      profession: 'Design Autoral & Alfaiataria',
      bio: 'Coleções exclusivas e atemporais em alta costura. Peças numeradas com entrega expressa para todo o Brasil.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
      phone: '(11) 99123-0000',
      whatsapp: '5511991230000',
      whatsappMessage: 'Olá! Vim pelo NaBio e gostaria de consultar a nova coleção do Atelier Noir.',
      whatsappButtonText: 'Falar com Concierge',
      email: 'concierge@noiratelier.com.br',
      theme: {
        primaryColor: '#ffffff',
        secondaryColor: '#e4e4e7',
        backgroundColor: '#09090b',
        backgroundType: 'video',
        backgroundVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-dark-ink-swirling-in-water-43309-large.mp4',
        backgroundOverlayOpacity: 65,
        backgroundBlur: 2,
        textColor: '#ffffff',
        subtextColor: '#a1a1aa',
        buttonColor: '#ffffff',
        buttonTextColor: '#000000',
        buttonStyle: 'filled',
        buttonBorderRadius: 'full',
        cardStyle: 'glass',
        cardBorderRadius: '2xl',
        cardShadow: 'glow',
        fontFamily: 'Plus Jakarta Sans',
        fontSize: 'base',
        catalogLayout: 'cards',
        showCoverImage: true,
        coverImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
      },
      pix: {
        enabled: true,
        keyType: 'cnpj',
        pixKey: '33.109.821/0001-44',
        receiverName: 'Noir Concept Studio Ltda',
        city: 'São Paulo',
        suggestedAmounts: [150, 300, 500, 1000],
        description: 'Pagamento de pedidos e reservas exclusivas',
      },
      wifi: {
        enabled: true,
        ssid: 'Noir_Studio_Private',
        password: 'conceptluxury',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Rua Oscar Freire',
        number: '890',
        neighborhood: 'Jardins',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01426-001',
        complement: 'Piso Superior',
      },
      categories: [
        { id: 'cat-n1', name: 'Nova Coleção', order: 1, active: true },
        { id: 'cat-n2', name: 'Acessórios & Joias', order: 2, active: true },
        { id: 'cat-n3', name: 'Alta Costura', order: 3, active: true },
      ],
      products: [
        {
          id: 'prod-n1',
          categoryId: 'cat-n1',
          name: 'Blazer Oversized Noir Monocromático',
          description: 'Lã fria italiana com acabamento artesanal, botões em madrepérola escura e caimento estruturado.',
          imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
          images: [
            'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=80',
          ],
          videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-curved-lines-of-light-moving-in-the-dark-41484-large.mp4',
          badge: 'NOVIDADE',
          badgeColor: '#ffffff',
          price: 890.00,
          promotionalPrice: 750.00,
          available: true,
          order: 1,
          ctaText: 'Reservar Peça',
          ctaAction: 'whatsapp',
          views: 480,
          clicks: 192,
        },
        {
          id: 'prod-n2',
          categoryId: 'cat-n2',
          name: 'Óculos de Sol Minimalist Obsidian',
          description: 'Acetato italiano polido à mão com lentes de proteção total UVA/UVB polarizadas.',
          imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
          images: [
            'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=600&q=80',
          ],
          badge: 'PROMOÇÃO',
          badgeColor: '#e11d48',
          price: 490.00,
          promotionalPrice: 380.00,
          available: true,
          order: 2,
          ctaText: 'Comprar no WhatsApp',
          ctaAction: 'whatsapp',
          views: 310,
          clicks: 115,
        },
      ],
      services: [
        {
          id: 'srv-n1',
          name: 'Consultoria de Estilo & Alfaiataria sob Medida',
          durationMinutes: 90,
          price: 350.00,
          promotionalPrice: 280.00,
          description: 'Atendimento exclusivo no atelier com medição precisa e seleção de tecidos importados.',
          imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
          images: [
            'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80',
          ],
          videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-dark-ink-swirling-in-water-43309-large.mp4',
          badge: 'EXCLUSIVO',
          badgeColor: '#ffffff',
          active: true,
        },
      ],
      socialLinks: [
        { id: 'soc-n1', platform: 'instagram', name: 'Instagram', url: 'https://instagram.com/noiratelier', order: 1, active: true },
        { id: 'soc-n2', platform: 'whatsapp', name: 'WhatsApp', url: 'https://wa.me/5511991230000', order: 2, active: true },
      ],
      links: [
        {
          id: 'lnk-n1',
          title: 'LOOKBOOK Coleção Cápsula 2026',
          subtitle: 'Editorial completo em alta resolução',
          url: 'https://noiratelier.com.br/lookbook',
          highlight: true,
          badge: 'NOVO',
          order: 1,
          active: true,
          clicks: 620,
          bgColor: '#ffffff',
          textColor: '#000000',
        },
      ],
    },
  },
  {
    id: 'delivery-gourmet',
    name: 'Yakisabor Gourmet & Delivery',
    category: 'Restaurante',
    description: 'Ideal para restaurantes, delivery, hamburguerias e comida japonesa com catálogo completo e botão direto para pedir no WhatsApp.',
    previewThumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Delivery',
      name: 'Yakisabor Sushi & Poke',
      commercialName: 'Yakisabor Gastronomia',
      category: 'Restaurante & Delivery',
      profession: 'Culinária Oriental Contemporânea',
      bio: '🍣 O melhor da culinária japonesa e oriental no conforto da sua casa. Ingredientes frescos e entrega rápida todos os dias!',
      avatarUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=400&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1200&q=80',
      phone: '(11) 98765-4321',
      whatsapp: '5511987654321',
      whatsappMessage: 'Olá! Vim pelo NaBio e gostaria de fazer um pedido no Yakisabor.',
      whatsappButtonText: 'Pedir pelo WhatsApp',
      email: 'pedidos@yakisabor.com.br',
      theme: {
        primaryColor: '#059669', // Emerald
        secondaryColor: '#10b981',
        backgroundColor: '#0f172a', // Deep slate dark
        backgroundType: 'solid',
        textColor: '#f8fafc',
        subtextColor: '#94a3b8',
        buttonColor: '#059669',
        buttonTextColor: '#ffffff',
        buttonStyle: 'filled',
        buttonBorderRadius: 'lg',
        cardStyle: 'bordered',
        fontFamily: 'Plus Jakarta Sans',
        fontSize: 'base',
        catalogLayout: 'cards',
        showCoverImage: true,
        coverImageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1200&q=80',
      },
      pix: {
        enabled: true,
        keyType: 'cnpj',
        pixKey: '45.892.102/0001-90',
        receiverName: 'Yakisabor Alimentos Ltda',
        city: 'São Paulo',
        suggestedAmounts: [35, 50, 85, 120],
        description: 'Chave Pix para pagamentos de pedidos no Yakisabor',
      },
      wifi: {
        enabled: true,
        ssid: 'Yakisabor_Clientes_5G',
        password: 'sushi-delicioso',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Alameda dos Pescadores',
        number: '482',
        neighborhood: 'Vila Madalena',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '05432-000',
        complement: 'Esquina com a Rua Japão',
        mapsUrl: 'https://maps.google.com/?q=Vila+Madalena+Sao+Paulo',
      },
      categories: [
        { id: 'cat-1', name: 'Combinados Especiais', order: 1, active: true },
        { id: 'cat-2', name: 'Pokes & Saladas', order: 2, active: true },
        { id: 'cat-3', name: 'Sobremesas & Bebidas', order: 3, active: true },
      ],
      products: [
        {
          id: 'prod-1',
          categoryId: 'cat-1',
          name: 'Combinado Salmão Premium (32 peças)',
          description: 'Sashimis frescos trufados, niguiris maçaricados e uramakis especiais com raspa de limão siciliano.',
          imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=80',
          images: [
            'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=600&q=80',
          ],
          videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-coals-burning-in-a-barbecue-grill-42939-large.mp4',
          badge: 'PROMOÇÃO',
          badgeColor: '#dc2626',
          price: 119.90,
          promotionalPrice: 98.90,
          available: true,
          order: 1,
          ctaText: 'Pedir no WhatsApp',
          ctaAction: 'whatsapp',
          views: 342,
          clicks: 128,
        },
        {
          id: 'prod-2',
          categoryId: 'cat-1',
          name: 'Yakisoba Especial da Casa',
          description: 'Massa artesanal, legumes salteados, tiras de filet mignon e frango com molho oriental tradicional.',
          imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
          price: 54.00,
          available: true,
          order: 2,
          ctaText: 'Pedir no WhatsApp',
          ctaAction: 'whatsapp',
          views: 215,
          clicks: 64,
        },
        {
          id: 'prod-3',
          categoryId: 'cat-2',
          name: 'Poke Hawaii Salmão Fresh',
          description: 'Arroz japonês, cubos de salmão, manga, edamame, cenoura, chips de batata doce e molho ponzu.',
          imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
          price: 49.90,
          promotionalPrice: 44.90,
          available: true,
          order: 3,
          ctaText: 'Pedir no WhatsApp',
          ctaAction: 'whatsapp',
          views: 180,
          clicks: 52,
        },
      ],
      services: [
        {
          id: 'srv-1',
          name: 'Reserva de Mesa VIP (Até 6 pessoas)',
          durationMinutes: 120,
          price: 50.00,
          description: 'Reserva garantida para grupos com atendimento e sushiman exclusivo.',
          active: true,
        },
      ],
      socialLinks: [
        { id: 'soc-1', platform: 'instagram', name: 'Instagram', url: 'https://instagram.com/yakisabor', order: 1, active: true },
        { id: 'soc-2', platform: 'whatsapp', name: 'WhatsApp', url: 'https://wa.me/5511987654321', order: 2, active: true },
        { id: 'soc-3', platform: 'facebook', name: 'Facebook', url: 'https://facebook.com/yakisabor', order: 3, active: true },
      ],
      links: [
        {
          id: 'lnk-1',
          title: '🔥 Cardápio Digital Completo',
          subtitle: 'Veja fotos, preços e faça seu pedido online',
          url: 'https://yakisabor.com.br/cardapio',
          highlight: true,
          badge: 'Mais pedido',
          order: 1,
          active: true,
          clicks: 450,
          bgColor: '#059669',
          textColor: '#ffffff',
        },
        {
          id: 'lnk-2',
          title: '⭐ Avalie nossa comida no Google',
          subtitle: 'Sua opinião é fundamental pra nossa equipe',
          url: 'https://g.page/yakisabor/review',
          order: 2,
          active: true,
          clicks: 87,
        },
        {
          id: 'lnk-3',
          title: '🛵 Peça também pelo iFood',
          subtitle: 'Entrega rápida com cupons da semana',
          url: 'https://ifood.com.br',
          order: 3,
          active: true,
          clicks: 194,
        },
      ],
    },
  },
  {
    id: 'barbearia-classic',
    name: 'Barber Club Vintage',
    category: 'Barbearia',
    description: 'Estilo sóbrio e rústico para barbearias, salões e estúdios de estética com agendamento de horários.',
    previewThumbnail: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Barbearia',
      name: 'Black Beard Barbearia',
      commercialName: 'Black Beard Club',
      category: 'Barbearia & Estética Masculina',
      profession: 'Corte Clássico & Barba Terapia',
      bio: '✂️ Barba, cabelo, chopp gelado e sinuca. Agende seu horário com os mestres da tesoura e navalha em São Paulo.',
      avatarUrl: 'https://images.unsplash.com/photo-1517832606589-7629c3395909?auto=format&fit=crop&w=400&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=1200&q=80',
      phone: '(11) 97123-8899',
      whatsapp: '5511971238899',
      whatsappMessage: 'Olá! Vim pelo NaBio e gostaria de agendar um horário na Black Beard.',
      whatsappButtonText: 'Agendar pelo WhatsApp',
      email: 'contato@blackbeard.com.br',
      theme: {
        primaryColor: '#d97706', // Amber gold
        secondaryColor: '#f59e0b',
        backgroundColor: '#18181b', // Zinc 900
        backgroundType: 'solid',
        textColor: '#fafafa',
        subtextColor: '#a1a1aa',
        buttonColor: '#d97706',
        buttonTextColor: '#ffffff',
        buttonStyle: 'filled',
        buttonBorderRadius: 'md',
        cardStyle: 'bordered',
        fontFamily: 'Outfit',
        fontSize: 'base',
        catalogLayout: 'list',
        showCoverImage: true,
      },
      pix: {
        enabled: true,
        keyType: 'phone',
        pixKey: '11971238899',
        receiverName: 'Black Beard Barbearia',
        city: 'São Paulo',
        suggestedAmounts: [45, 60, 90, 130],
        description: 'Sinal para confirmação de agendamento',
      },
      wifi: {
        enabled: true,
        ssid: 'BlackBeard_Guest',
        password: 'choppebarbaclub',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Rua Augusta',
        number: '1420',
        neighborhood: 'Consolação',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01304-001',
        complement: 'Próximo ao Metrô',
      },
      categories: [
        { id: 'cat-b1', name: 'Serviços de Cabelo', order: 1, active: true },
        { id: 'cat-b2', name: 'Barba & Cuidados', order: 2, active: true },
        { id: 'cat-b3', name: 'Produtos para Levar', order: 3, active: true },
      ],
      products: [
        {
          id: 'prod-b1',
          categoryId: 'cat-b1',
          name: 'Corte Fade & Degradê Navalhado',
          description: 'Lavagem com produtos especiais, finalização pomada fosca e alinhamento do contorno.',
          price: 65.00,
          available: true,
          order: 1,
          ctaText: 'Agendar Horário',
          ctaAction: 'whatsapp',
          views: 180,
          clicks: 94,
        },
        {
          id: 'prod-b2',
          categoryId: 'cat-b2',
          name: 'Barboterapia Completa com Toalha Quente',
          description: 'Esfoliação facial, vapor de ozônio, hidratação profunda e óleo nutritivo.',
          price: 55.00,
          promotionalPrice: 45.00,
          available: true,
          order: 2,
          ctaText: 'Agendar Barba',
          ctaAction: 'whatsapp',
          views: 140,
          clicks: 72,
        },
      ],
      services: [
        { id: 's-1', name: 'Corte Masculino', durationMinutes: 40, price: 65, description: 'Corte completo com tesoura ou máquina', active: true },
        { id: 's-2', name: 'Barba Clássica', durationMinutes: 30, price: 50, description: 'Design de barba com navalha', active: true },
        { id: 's-3', name: 'Combo Cabelo + Barba', durationMinutes: 60, price: 100, description: 'Experiência completa relaxante', active: true },
      ],
      socialLinks: [
        { id: 'sb-1', platform: 'instagram', name: 'Instagram', url: 'https://instagram.com', order: 1, active: true },
        { id: 'sb-2', platform: 'whatsapp', name: 'WhatsApp', url: 'https://wa.me/5511971238899', order: 2, active: true },
      ],
      links: [
        {
          id: 'lb-1',
          title: '📅 Agendamento Online Rápido',
          subtitle: 'Escolha o profissional e horário disponível',
          url: 'https://agendamento.blackbeard.com.br',
          highlight: true,
          order: 1,
          active: true,
          clicks: 310,
        },
      ],
    },
  },
  {
    id: 'dentista-saude',
    name: 'Clínica Odonto Prime & Saúde',
    category: 'Dentista',
    description: 'Design limpo, confiável e profissional em tons de azul e ciano para médicos, dentistas e clínicas.',
    previewThumbnail: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Dentista',
      name: 'Dra. Camila Vasconcelos',
      commercialName: 'Odonto Prime Estética',
      category: 'Odontologia & Harmonização Facial',
      profession: 'Especialista em Lentes de Resina e Ortodontia Invisível',
      bio: 'Transformando sorrisos com odontologia moderna e sem dor. Mais de 2.000 pacientes transformados. CRO-SP 114.920.',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
      phone: '(11) 3214-5500',
      whatsapp: '5511933445566',
      whatsappMessage: 'Olá Dra. Camila! Vim pelo NaBio e gostaria de agendar uma consulta de avaliação.',
      whatsappButtonText: 'Marcar Avaliação',
      email: 'contato@dracamilasorrisos.com.br',
      theme: {
        primaryColor: '#0284c7', // Sky 600
        secondaryColor: '#0ea5e9',
        backgroundColor: '#f8fafc', // Clean light slate
        backgroundType: 'solid',
        textColor: '#0f172a',
        subtextColor: '#64748b',
        buttonColor: '#0284c7',
        buttonTextColor: '#ffffff',
        buttonStyle: 'filled',
        buttonBorderRadius: 'full',
        cardStyle: 'elevated',
        fontFamily: 'Plus Jakarta Sans',
        fontSize: 'base',
        catalogLayout: 'grid',
        showCoverImage: true,
      },
      pix: {
        enabled: true,
        keyType: 'email',
        pixKey: 'pix@dracamilasorrisos.com.br',
        receiverName: 'Camila Vasconcelos Odontologia',
        city: 'São Paulo',
        suggestedAmounts: [150, 300, 500],
        description: 'Consulta de avaliação ortodôntica',
      },
      wifi: {
        enabled: true,
        ssid: 'OdontoPrime_Consultorio',
        password: 'sorriso-perfeito',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Avenida Paulista',
        number: '2073',
        neighborhood: 'Bela Vista',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01311-300',
        complement: 'Conjunto 142 - 14º andar (Edifício Horsa II)',
      },
      categories: [
        { id: 'cat-d1', name: 'Tratamentos Estéticos', order: 1, active: true },
        { id: 'cat-d2', name: 'Ortodontia & Alinhadores', order: 2, active: true },
      ],
      products: [
        {
          id: 'prod-d1',
          categoryId: 'cat-d1',
          name: 'Clareamento Dental a Laser',
          description: 'Sessão em consultório para dentes visivelmente mais brancos com total proteção do esmalte.',
          price: 650.00,
          promotionalPrice: 490.00,
          available: true,
          order: 1,
          ctaText: 'Saber Mais',
          ctaAction: 'whatsapp',
          views: 290,
          clicks: 110,
        },
      ],
      services: [
        { id: 'sd-1', name: 'Consulta Inicial & Check-up Digital', durationMinutes: 50, price: 180, description: 'Avaliação detalhada com câmera intraoral e raio-X digital', active: true },
      ],
      socialLinks: [
        { id: 'so-1', platform: 'instagram', name: 'Instagram', url: 'https://instagram.com', order: 1, active: true },
        { id: 'so-2', platform: 'linkedin', name: 'LinkedIn', url: 'https://linkedin.com', order: 2, active: true },
        { id: 'so-3', platform: 'whatsapp', name: 'WhatsApp', url: 'https://wa.me/5511933445566', order: 3, active: true },
      ],
      links: [
        {
          id: 'ld-1',
          title: '🦷 Agendar Consulta de Avaliação',
          subtitle: 'Atendimento humanizado e sem fila de espera',
          url: 'https://wa.me/5511933445566',
          highlight: true,
          order: 1,
          active: true,
          clicks: 420,
        },
        {
          id: 'ld-2',
          title: '📸 Antes e Depois de Pacientes',
          subtitle: 'Veja transformações reais em nosso Instagram',
          url: 'https://instagram.com',
          order: 2,
          active: true,
          clicks: 198,
        },
      ],
    },
  },
  {
    id: 'loja-moda',
    name: 'Aura Concept Store',
    category: 'Loja',
    description: 'Minimalista e visualmente sofisticado para lojas de roupas, joias, calçados e cosméticos.',
    previewThumbnail: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Loja',
      name: 'Aura Concept Store',
      commercialName: 'Aura Moda & Design',
      category: 'Moda Feminina Autoral',
      profession: 'Designers Brasileiras & Peças Atemporais',
      bio: '✨ Peças exclusivas produzidas com tecidos nobres e acabamento de alta alfaiataria. Enviamos para todo o Brasil.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
      whatsapp: '5511998877665',
      whatsappMessage: 'Olá! Adorei as peças no NaBio e gostaria de consultar a disponibilidade no meu tamanho.',
      whatsappButtonText: 'Falar com Consultora',
      email: 'sac@auraconcept.com.br',
      theme: {
        primaryColor: '#e11d48', // Rose
        secondaryColor: '#f43f5e',
        backgroundColor: '#ffffff',
        backgroundType: 'solid',
        textColor: '#1c1917',
        subtextColor: '#78716c',
        buttonColor: '#1c1917',
        buttonTextColor: '#ffffff',
        buttonStyle: 'filled',
        buttonBorderRadius: 'none',
        cardStyle: 'flat',
        fontFamily: 'Plus Jakarta Sans',
        fontSize: 'base',
        catalogLayout: 'grid',
        showCoverImage: true,
      },
      pix: {
        enabled: true,
        keyType: 'cnpj',
        pixKey: '29.345.678/0001-12',
        receiverName: 'Aura Store Comercio Ltda',
        city: 'São Paulo',
        suggestedAmounts: [120, 250, 480],
      },
      wifi: {
        enabled: true,
        ssid: 'Aura_Store_WiFi',
        password: 'vestir-com-alma',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Rua Oscar Freire',
        number: '890',
        neighborhood: 'Cerqueira César',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01426-001',
      },
      categories: [
        { id: 'cl-1', name: 'Nova Coleção Outono', order: 1, active: true },
        { id: 'cl-2', name: 'Alfaiataria & Blusas', order: 2, active: true },
      ],
      products: [
        {
          id: 'pl-1',
          categoryId: 'cl-1',
          name: 'Blazer Linho Puro Terracota',
          description: 'Modelagem ampla, corte impecável, botões em madrepérola natural.',
          imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
          price: 389.00,
          promotionalPrice: 329.00,
          available: true,
          order: 1,
          ctaText: 'Comprar no WhatsApp',
          ctaAction: 'whatsapp',
          views: 380,
          clicks: 140,
        },
      ],
      services: [],
      socialLinks: [
        { id: 'sl-1', platform: 'instagram', name: 'Instagram', url: 'https://instagram.com', order: 1, active: true },
        { id: 'sl-2', platform: 'tiktok', name: 'TikTok', url: 'https://tiktok.com', order: 2, active: true },
      ],
      links: [
        {
          id: 'll-1',
          title: '🛍️ Acessar E-commerce Oficial',
          subtitle: 'Frete Grátis nas compras acima de R$ 299',
          url: 'https://auraconcept.com.br',
          highlight: true,
          order: 1,
          active: true,
          clicks: 520,
        },
      ],
    },
  },
  {
    id: 'prestador-servico',
    name: 'Resolve Já Instalações & Manutenção',
    category: 'Prestador de serviço',
    description: 'Foco em chamada direta, WhatsApp, orçamento rápido e atendimento emergencial.',
    previewThumbnail: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
    defaultData: {
      businessType: 'Prestador de serviço',
      name: 'Carlos Mendes Manutenções',
      commercialName: 'Resolve Já Reparos Rápidos',
      category: 'Eletricista & Manutenção Residencial',
      profession: 'Eletricista Credenciado e Climatização',
      bio: '⚡ Instalações elétricas, ar-condicionado, cabeamento e reparos rápidos com nota fiscal e garantia de 1 ano.',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
      phone: '(11) 98111-2233',
      whatsapp: '5511981112233',
      whatsappMessage: 'Olá Carlos! Vim pelo NaBio e preciso de um orçamento urgente para instalação.',
      whatsappButtonText: 'Solicitar Orçamento Grátis',
      email: 'carlos@resolveja.com.br',
      theme: {
        primaryColor: '#2563eb', // Blue
        secondaryColor: '#3b82f6',
        backgroundColor: '#f1f5f9',
        backgroundType: 'solid',
        textColor: '#0f172a',
        subtextColor: '#475569',
        buttonColor: '#2563eb',
        buttonTextColor: '#ffffff',
        buttonStyle: 'filled',
        buttonBorderRadius: 'md',
        cardStyle: 'bordered',
        fontFamily: 'Plus Jakarta Sans',
        fontSize: 'base',
        catalogLayout: 'list',
        showCoverImage: false,
      },
      pix: {
        enabled: true,
        keyType: 'cpf',
        pixKey: '284.192.839-01',
        receiverName: 'Carlos Eduardo Mendes',
        city: 'São Paulo',
        suggestedAmounts: [80, 150, 250, 400],
      },
      wifi: {
        enabled: false,
        ssid: '',
        password: '',
        securityType: 'WPA',
        hidden: false,
      },
      location: {
        enabled: true,
        street: 'Atendimento em toda Grande São Paulo e ABC',
        number: '',
        neighborhood: '',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01000-000',
      },
      categories: [
        { id: 'cps-1', name: 'Elétrica Residencial', order: 1, active: true },
        { id: 'cps-2', name: 'Ar-Condicionado', order: 2, active: true },
      ],
      products: [
        {
          id: 'pps-1',
          categoryId: 'cps-1',
          name: 'Instalação de Chuveiro e Disjuntores',
          description: 'Troca de fiação, verificação de aterramento e teste de carga.',
          price: 120.00,
          available: true,
          order: 1,
          ctaText: 'Pedir Orçamento',
          ctaAction: 'whatsapp',
          views: 120,
          clicks: 65,
        },
      ],
      services: [
        { id: 'sps-1', name: 'Visita Técnica de Diagnóstico', durationMinutes: 60, price: 80, description: 'Valor abatido no fechamento do serviço', active: true },
      ],
      socialLinks: [
        { id: 'spsl-1', platform: 'whatsapp', name: 'WhatsApp', url: 'https://wa.me/5511981112233', order: 1, active: true },
        { id: 'spsl-2', platform: 'facebook', name: 'Facebook', url: 'https://facebook.com', order: 2, active: true },
      ],
      links: [
        {
          id: 'lps-1',
          title: '⚡ Chamar no WhatsApp Agora',
          subtitle: 'Resposta média em menos de 10 minutos',
          url: 'https://wa.me/5511981112233',
          highlight: true,
          order: 1,
          active: true,
          clicks: 290,
        },
      ],
    },
  },
];
